apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-backstage-app
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    github.com/project-slug: qd289942/backstage_test
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: qd289942
  lifecycle: experimental
